services:
  - type: web
    name: beautybreeze-web
    env: docker
    plan: standard
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
    # Build & start are handled by your Dockerfile:
    buildCommand: ""    # handled by Dockerfile
    startCommand: ""    # handled by Dockerfile

  - type: worker
    name: beautybreeze-worker
    env: docker
    autoDeploy: true
    startCommand: php artisan queue:work --tries=3 --sleep=1

jobs:
  - type: cron
    name: beautybreeze-scheduler
    schedule: "* * * * *"
    env: docker
    command: php artisan schedule:run
