services:
  - type: web
    name: beautybreeze-web
    env: docker
    plan: standard
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr

  - type: worker
    name: beautybreeze-worker
    env: docker
    autoDeploy: true
    dockerCommand: php artisan queue:work --tries=3 --sleep=1

